module.exports = {
  ADD_POST: 'ADD_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  REQUEST_POSTS: 'REQUEST_POSTS',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  REQUEST_PROJECTS: 'REQUEST_PROJECTS',
  RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
  SEARCH_TERM: 'SEARCH_TERM',
};
