export default {
  // Posts
  ADD_POST: 'ADD_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  REQUEST_POSTS: 'REQUEST_POSTS',
  REQUEST_POSTS_ERROR: 'REQUEST_POSTS_ERROR',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  // Projects
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  REQUEST_PROJECTS: 'REQUEST_PROJECTS',
  REQUEST_PROJECTS_ERROR: 'REQUEST_PROJECTS_ERROR',
  RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
  // Search
  SEARCH_TERM: 'SEARCH_TERM',
};
